# Generated by Django 2.0.6 on 2018-06-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180610_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='os_android',
        ),
        migrations.RemoveField(
            model_name='product',
            name='os_ios',
        ),
    ]
