# Generated by Django 2.0.6 on 2018-06-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180610_1313'),
    ]

    operations = [
    ]
