# Generated by Django 2.0.6 on 2018-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Prodcuts',
            new_name='products',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
